version: '3'

services:
  php:
    image: php:latest

  nginx:
    image: nginx:latest

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "testDB"
      POSTGRES_USER: "retmix"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5432:5432"

  adminer:
    image: adminer:latest
    